### PR TITLE
Added onSliding function

### PR DESCRIPTION
**Pull request by sharadsxn24**
I have added a utility function onSliding(percentage:number).

This function will be called when the side menu is sliding, it will return a percentage number. The number represents the percent of sliding animation completed by the side menu.

@Kureev Please review the PR and provide any feedbacks. I will happy to update the docs as well.

### CODE REVIEW

**Comment by Kureev** [comment]
Hi @sharadsxn24!

Great PR! I love it ❤️ ! The only thing I'd like to see before merging this is documentation. Could you be so kind to add it to the API list and outline a use case in a couple of words?

Thanks for this once again!

**Comment by Kureev** [comment]
Awesome! Thanks for your hard work!

**Comment by sharadsxn24** [comment]
Hi @Kureev, 

Thanks for your words of appreciation. :)
I have made a slight fix and updated the documentation.

But first of all, thanks for the awesome repo. It helped me alot 👍

**Comment by Kureev** [comment]
Released 1.1.0 with this API

**Pull request merged**
