### PR TITLE
Add typescript definitions

### PR DESCRIPTION
**Pull request by jsamr**

### CODE REVIEW

**Comment by kishanio** [comment]
@Kureev Can you merge this please?

**Comment by l-Marty-l** [comment]
I'd love to see this merged, please!

**Comment by nferrara100** [comment]
Can't wait to see this merged!

**Comment by jsamr** [comment]
Closing, because a DefinitelyTyped PR is on its way.
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44583

**Comment by toughdeveloper** [comment]
For anyone finding this link, it got published - https://www.npmjs.com/package/@types/react-native-side-menu

Types can therefore be installed with `npm i @types/react-native-side-menu --save-dev`

**Pull request closed without merging**
