### PR TITLE
Added Loading Time Invisible

### PR DESCRIPTION
**Pull request by aleixrodri98**
I've added some loading time before the menu appears. 

If you could please implement this.

### CODE REVIEW

**Comment by Kureev** [comment]
I'm not sure why we need it?

**Comment by aleixrodri98** [comment]
Because if not, the menu appears in front of the content when opening the app, in front of the splashcreen

**Comment by Kureev** [comment]
Do you have a custom splash screen implemented by yourself?
iOS splash screen (not sure about Android) can't be overlapped by a RN view. Can you please provide more details on your issue so we'll figure out the solution 😉

**Comment by Kureev** [comment]
Closed due to lack of feedback

**Pull request closed without merging**
